
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${LOCAL_PORT}:80
  node:
    image: "node:16.15.0-alpine"
    working_dir: /opt/front
    volumes:
      - ${FRONTEND}:/opt/front
      - /opt/front/node_modules
    entrypoint: "/bin/sh -c 'npm install && npm run dev'"
  env:
    image: "golang:1.18.2"
    restart: on-failure
    environment:
      - GO111MODULE=on
      - PORT=8080
      - APP_URL=http://localhost:${LOCAL_PORT}
    working_dir: /opt/app
    volumes:
      - ${BACKEND}:/opt/app
      - /opt/app/tmp
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro


    command: /bin/sh -c 'go install github.com/cosmtrek/air@latest && air'